runtime: nodejs14
instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  max_idle_instances: 1
  target_cpu_utilization: 0.7
  max_concurrent_requests: 40

vpc_access_connector:
  name: projects/swaysocial-one-pager/locations/europe-west1/connectors/app-engine-eu-w
  egress_setting: all-traffic