export interface Claim {
  _id: string,
  log_index: number,
  transaction_hash: string,
  _created_at: Date,
  _updated_at: Date,
  address: string,
  swayAmount: string,
  swayAmount_decimal: number,
  block_hash: number,
  block_number: number,
  block_timestamp: Date,
  confirmed: boolean,
  poolHandle: string,
  recipient: string,
  transaction_index: number,
}
